{{- if .Values.nimPipelineRetriever.enabled }}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMPipeline
metadata:
  name: {{ .Values.nimPipelineRetriever.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  services:
    - name: {{ .Values.nimPipelineRetriever.serviceName }}
      enabled: true
      spec:
        image:
          repository: {{ .Values.nimPipelineRetriever.image.repository }}
          tag: {{ .Values.nimPipelineRetriever.image.tag | quote }}
          pullPolicy: {{ .Values.nimPipelineRetriever.image.pullPolicy }}
          pullSecrets:
          - {{ .Values.nimPipelineRetriever.pullSecret }}
        authSecret: {{ .Values.nimPipelineRetriever.authSecret }}
        storage:
          nimCache:
            name: {{ .Values.nimPipelineRetriever.nimCacheName }}
            profile: ''
        replicas: {{ .Values.nimPipelineRetriever.replicas }}
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.nimPipelineRetriever.resources.limits.gpu }}
        # GPU node tolerations for OpenShift/Kubernetes clusters with tainted GPU nodes
        tolerations:
{{- toYaml .Values.nimPipelineRetriever.tolerations | nindent 10 }}
        expose:
          service:
            type: ClusterIP
            port: 8000
{{- end }}
